name: Deploy To NCloud-Server

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 로드
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application.yml 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml

      - name: 도커 이미지 생성
        run: docker build -t re-memory-server ./api
